"""Code-first module registry — Phase 14D-B2a."""

from registry.nav_keys import (
    NAV_AUDIT_LOG,
    NAV_BACKUP_RESTORE,
    NAV_BALANCE_SHEET,
    NAV_BANKING,
    NAV_BUDGET,
    NAV_CASH_FLOW,
    NAV_CASH_RECONCILIATION,
    NAV_CHART_OF_ACCOUNTS,
    NAV_COMPANY_SETTINGS,
    NAV_CUSTOMERS,
    NAV_END_OF_DAY_CLOSE,
    NAV_EXPENSES,
    NAV_FISCAL_PERIODS,
    NAV_GENERAL_LEDGER,
    NAV_HOME,
    NAV_INVENTORY,
    NAV_JOURNAL_ENTRIES,
    NAV_MEMBERS,
    NAV_MY_ACCOUNT,
    NAV_NEW_TRANSACTION,
    NAV_OPENING_BALANCES,
    NAV_PARTNER_ACCOUNTS,
    NAV_PAYABLES,
    NAV_PURCHASES,
    NAV_PROFIT_LOSS,
    NAV_RECEIVABLES,
    NAV_RECURRING_EXPENSES,
    NAV_REPORTS,
    NAV_RECON_HEALTH,
    NAV_SALES,
    NAV_TODAY_SUMMARY,
    NAV_TRIAL_BALANCE,
    NAV_TXN_LEDGER,
    NAV_VENDORS,
    NAV_WORKERS,
    NAV_YEAR_END_CLOSE,
)
from registry.types import ModuleDef

MODULES: tuple[ModuleDef, ...] = (
    # ── Core (shipped) ───────────────────────────────────────────────────────
    ModuleDef("dashboard", "nav.dashboard", "operations", nav_page=NAV_HOME),
    ModuleDef("new_transaction", "nav.new_transaction", "operations", nav_page=NAV_NEW_TRANSACTION),
    ModuleDef(
        "transaction_ledger",
        "nav.transaction_ledger",
        "operations",
        nav_page=NAV_TXN_LEDGER,
    ),
    ModuleDef("sales", "nav.sales", "operations", nav_page=NAV_SALES),
    ModuleDef("expenses", "nav.expenses", "operations", nav_page=NAV_EXPENSES),
    ModuleDef(
        "recurring_expenses",
        "nav.recurring_expenses",
        "operations",
        nav_page=NAV_RECURRING_EXPENSES,
    ),
    ModuleDef("purchases", "nav.purchases", "operations", nav_page=NAV_PURCHASES),
    ModuleDef(
        "cash_reconciliation",
        "nav.cash_reconciliation",
        "operations",
        nav_page=NAV_CASH_RECONCILIATION,
    ),
    ModuleDef(
        "end_of_day_close",
        "nav.end_of_day_close",
        "operations",
        nav_page=NAV_END_OF_DAY_CLOSE,
    ),
    ModuleDef("customers", "nav.customers", "crm", nav_page=NAV_CUSTOMERS),
    ModuleDef("vendors", "nav.vendors", "crm", nav_page=NAV_VENDORS),
    ModuleDef("receivables", "nav.receivables", "crm", nav_page=NAV_RECEIVABLES),
    ModuleDef("payables", "nav.payables", "crm", nav_page=NAV_PAYABLES),
    ModuleDef("inventory", "nav.inventory", "operations", nav_page=NAV_INVENTORY, company_toggleable=True),
    ModuleDef("banking", "nav.banking", "operations", nav_page=NAV_BANKING),
    ModuleDef("reports", "nav.reports", "reporting", nav_page=NAV_REPORTS),
    ModuleDef("profit_loss", "nav.profit_loss", "reporting", nav_page=NAV_PROFIT_LOSS),
    ModuleDef("balance_sheet", "nav.balance_sheet", "reporting", nav_page=NAV_BALANCE_SHEET),
    ModuleDef("cash_flow", "nav.cash_flow", "reporting", nav_page=NAV_CASH_FLOW),
    ModuleDef("general_ledger", "nav.general_ledger", "accounting", nav_page=NAV_GENERAL_LEDGER),
    ModuleDef("trial_balance", "nav.trial_balance", "accounting", nav_page=NAV_TRIAL_BALANCE),
    ModuleDef("journal_entries", "nav.journal_entries", "accounting", nav_page=NAV_JOURNAL_ENTRIES),
    ModuleDef("fiscal_periods", "nav.fiscal_periods", "accounting", nav_page=NAV_FISCAL_PERIODS),
    ModuleDef("year_end_close", "nav.year_end_close", "accounting", nav_page=NAV_YEAR_END_CLOSE),
    ModuleDef("budget", "nav.budget", "accounting", nav_page=NAV_BUDGET),
    ModuleDef("chart_of_accounts", "nav.chart_of_accounts", "accounting", nav_page=NAV_CHART_OF_ACCOUNTS),
    ModuleDef("recon_health", "nav.recon_health", "accounting", nav_page=NAV_RECON_HEALTH),
    ModuleDef("partner_accounts", "nav.partner_accounts", "administration", nav_page=NAV_PARTNER_ACCOUNTS),
    ModuleDef("workers", "nav.workers", "administration", nav_page=NAV_WORKERS),
    ModuleDef("opening_balances", "nav.opening_balances", "administration", nav_page=NAV_OPENING_BALANCES),
    ModuleDef("company_settings", "nav.company_settings", "administration", nav_page=NAV_COMPANY_SETTINGS),
    ModuleDef("users", "nav.users", "administration", nav_page=NAV_MEMBERS),
    ModuleDef("audit_log", "nav.audit_log", "administration", nav_page=NAV_AUDIT_LOG),
    ModuleDef("backup_restore", "nav.backup_restore", "administration", nav_page=NAV_BACKUP_RESTORE),
    ModuleDef("my_account", "nav.my_account", "administration", nav_page=NAV_MY_ACCOUNT, user_hideable=False),
    # ── Planned modules (metadata only) ──────────────────────────────────────
    ModuleDef(
        "foreign_currency",
        "nav.foreign_currency",
        "planned",
        planned=True,
        company_toggleable=True,
        entitlement="fx",
        dependencies=("accounting.multi_currency_enabled",),
    ),
    ModuleDef(
        "credit_cards",
        "nav.credit_cards",
        "planned",
        planned=True,
        company_toggleable=True,
        entitlement="banking_pro",
    ),
    ModuleDef(
        "bank_statement_import",
        "nav.bank_statement_import",
        "planned",
        planned=True,
        company_toggleable=True,
        dependencies=("banking",),
        entitlement="banking_pro",
    ),
    ModuleDef(
        "vat_tax",
        "nav.vat_tax",
        "planned",
        planned=True,
        company_toggleable=True,
        dependencies=("policy.vat_enabled",),
        entitlement="tax",
    ),
)

# Nav pages registered in app.py _PAGE_DISPATCH.
NAV_PAGES_IN_APP = frozenset(
    {
        NAV_HOME,
        NAV_TODAY_SUMMARY,
        NAV_NEW_TRANSACTION,
        NAV_TXN_LEDGER,
        NAV_SALES,
        NAV_EXPENSES,
        NAV_RECURRING_EXPENSES,
        NAV_PURCHASES,
        NAV_CASH_RECONCILIATION,
        NAV_END_OF_DAY_CLOSE,
        NAV_CUSTOMERS,
        NAV_VENDORS,
        NAV_RECEIVABLES,
        NAV_PAYABLES,
        NAV_INVENTORY,
        NAV_BANKING,
        NAV_REPORTS,
        NAV_PROFIT_LOSS,
        NAV_BALANCE_SHEET,
        NAV_CASH_FLOW,
        NAV_GENERAL_LEDGER,
        NAV_TRIAL_BALANCE,
        NAV_JOURNAL_ENTRIES,
        NAV_FISCAL_PERIODS,
        NAV_YEAR_END_CLOSE,
        NAV_BUDGET,
        NAV_CHART_OF_ACCOUNTS,
        NAV_RECON_HEALTH,
        NAV_COMPANY_SETTINGS,
        NAV_PARTNER_ACCOUNTS,
        NAV_WORKERS,
        NAV_MEMBERS,
        NAV_AUDIT_LOG,
        NAV_BACKUP_RESTORE,
        NAV_OPENING_BALANCES,
        NAV_MY_ACCOUNT,
    }
)
