"""Code-first module registry — Phase 14D-B2a."""

from registry.types import ModuleDef

MODULES: tuple[ModuleDef, ...] = (
    # ── Core (shipped) ───────────────────────────────────────────────────────
    ModuleDef("dashboard", "nav.dashboard", "operations", nav_page="🏠 Home"),
    ModuleDef("new_transaction", "nav.new_transaction", "operations", nav_page="➕ New Transaction"),
    ModuleDef(
        "transaction_ledger",
        "nav.transaction_ledger",
        "operations",
        nav_page="📒 Transaction Ledger",
    ),
    ModuleDef("sales", "nav.sales", "operations", nav_page="💼 Sales"),
    ModuleDef("expenses", "nav.expenses", "operations", nav_page="💳 Expenses"),
    ModuleDef(
        "recurring_expenses",
        "nav.recurring_expenses",
        "operations",
        nav_page="🔁 Recurring Expenses",
    ),
    ModuleDef("purchases", "nav.purchases", "operations", nav_page="🛒 Purchases"),
    ModuleDef(
        "cash_reconciliation",
        "nav.cash_reconciliation",
        "operations",
        nav_page="💸 Cash Reconciliation",
    ),
    ModuleDef(
        "end_of_day_close",
        "nav.end_of_day_close",
        "operations",
        nav_page="🌙 End-of-Day Close",
    ),
    ModuleDef("customers", "nav.customers", "crm", nav_page="👥 Customers"),
    ModuleDef("vendors", "nav.vendors", "crm", nav_page="🏢 Vendors"),
    ModuleDef("receivables", "nav.receivables", "crm", nav_page="📄 Receivables"),
    ModuleDef("payables", "nav.payables", "crm", nav_page="📌 Payables"),
    ModuleDef("inventory", "nav.inventory", "operations", nav_page="📦 Inventory", company_toggleable=True),
    ModuleDef("banking", "nav.banking", "operations", nav_page="🏦 Banking"),
    ModuleDef("reports", "nav.reports", "reporting", nav_page="📊 Reports"),
    ModuleDef("profit_loss", "nav.profit_loss", "reporting", nav_page="💰 Profit & Loss"),
    ModuleDef("balance_sheet", "nav.balance_sheet", "reporting", nav_page="🏛️ Balance Sheet"),
    ModuleDef("cash_flow", "nav.cash_flow", "reporting", nav_page="💸 Cash Flow"),
    ModuleDef("general_ledger", "nav.general_ledger", "accounting", nav_page="🗂 General Ledger"),
    ModuleDef("trial_balance", "nav.trial_balance", "accounting", nav_page="⚖️ Trial Balance"),
    ModuleDef("journal_entries", "nav.journal_entries", "accounting", nav_page="📓 Journal Entries"),
    ModuleDef("fiscal_periods", "nav.fiscal_periods", "accounting", nav_page="🗓 Fiscal Periods"),
    ModuleDef("year_end_close", "nav.year_end_close", "accounting", nav_page="📆 Year-End Close"),
    ModuleDef("budget", "nav.budget", "accounting", nav_page="💰 Budget"),
    ModuleDef("chart_of_accounts", "nav.chart_of_accounts", "accounting", nav_page="🔍 Chart of Accounts"),
    ModuleDef("recon_health", "nav.recon_health", "accounting", nav_page="🩺 Recon Health"),
    ModuleDef("partner_accounts", "nav.partner_accounts", "administration", nav_page="🏦 Partner Accounts"),
    ModuleDef("workers", "nav.workers", "administration", nav_page="👷 Workers"),
    ModuleDef("opening_balances", "nav.opening_balances", "administration", nav_page="⚡ Opening Balances"),
    ModuleDef("company_settings", "nav.company_settings", "administration", nav_page="🏢 Company Settings"),
    ModuleDef("users", "nav.users", "administration", nav_page="👤 Members"),
    ModuleDef("audit_log", "nav.audit_log", "administration", nav_page="🕵️ Audit Log"),
    ModuleDef("backup_restore", "nav.backup_restore", "administration", nav_page="💾 Backup & Restore"),
    ModuleDef("my_account", "nav.my_account", "administration", nav_page="👤 My Account", user_hideable=False),
    # ── Planned modules (metadata only) ──────────────────────────────────────
    ModuleDef(
        "foreign_currency",
        "nav.foreign_currency",
        "planned",
        planned=True,
        company_toggleable=True,
        entitlement="fx",
        dependencies=("accounting.multi_currency_enabled",),
    ),
    ModuleDef(
        "credit_cards",
        "nav.credit_cards",
        "planned",
        planned=True,
        company_toggleable=True,
        entitlement="banking_pro",
    ),
    ModuleDef(
        "bank_statement_import",
        "nav.bank_statement_import",
        "planned",
        planned=True,
        company_toggleable=True,
        dependencies=("banking",),
        entitlement="banking_pro",
    ),
    ModuleDef(
        "vat_tax",
        "nav.vat_tax",
        "planned",
        planned=True,
        company_toggleable=True,
        dependencies=("policy.vat_enabled",),
        entitlement="tax",
    ),
)

# Nav pages registered in app.py _PAGE_DISPATCH.
NAV_PAGES_IN_APP = frozenset(
    {
        "🏠 Home",
        "📅 Today's Summary",
        "➕ New Transaction",
        "📒 Transaction Ledger",
        "💼 Sales",
        "💳 Expenses",
        "🔁 Recurring Expenses",
        "🛒 Purchases",
        "💸 Cash Reconciliation",
        "🌙 End-of-Day Close",
        "👥 Customers",
        "🏢 Vendors",
        "📄 Receivables",
        "📌 Payables",
        "📦 Inventory",
        "🏦 Banking",
        "📊 Reports",
        "💰 Profit & Loss",
        "🏛️ Balance Sheet",
        "💸 Cash Flow",
        "🗂 General Ledger",
        "⚖️ Trial Balance",
        "📓 Journal Entries",
        "🗓 Fiscal Periods",
        "📆 Year-End Close",
        "💰 Budget",
        "🔍 Chart of Accounts",
        "🩺 Recon Health",
        "🏢 Company Settings",
        "🏦 Partner Accounts",
        "👷 Workers",
        "👤 Members",
        "🕵️ Audit Log",
        "💾 Backup & Restore",
        "⚡ Opening Balances",
        "👤 My Account",
    }
)
