"""Canonical nav page keys → i18n message keys (Phase 15)."""

from __future__ import annotations

from registry.nav_keys import (
    NAV_AUDIT_LOG,
    NAV_BACKUP_RESTORE,
    NAV_BALANCE_SHEET,
    NAV_BANKING,
    NAV_BUDGET,
    NAV_CASH_FLOW,
    NAV_CASH_RECONCILIATION,
    NAV_CHART_OF_ACCOUNTS,
    NAV_COMPANY_SETTINGS,
    NAV_CUSTOMERS,
    NAV_END_OF_DAY_CLOSE,
    NAV_EXPENSES,
    NAV_EXTERNAL_SALES_VERIFICATION,
    NAV_FISCAL_PERIODS,
    NAV_GENERAL_LEDGER,
    NAV_HOME,
    NAV_INVENTORY,
    NAV_JOURNAL_ENTRIES,
    NAV_MEMBERS,
    NAV_MY_ACCOUNT,
    NAV_NEW_TRANSACTION,
    NAV_OPENING_BALANCES,
    NAV_PARTNER_ACCOUNTS,
    NAV_PAYABLES,
    NAV_PERMISSIONS,
    NAV_PROFIT_LOSS,
    NAV_PURCHASES,
    NAV_RC_COST_BREAKDOWN,
    NAV_RC_INGREDIENTS,
    NAV_RC_MENU_ITEMS,
    NAV_RC_RECIPES,
    NAV_RECEIVABLES,
    NAV_RECON_HEALTH,
    NAV_RECURRING_EXPENSES,
    NAV_REPORTS,
    NAV_SALES,
    NAV_TODAY_SUMMARY,
    NAV_TRIAL_BALANCE,
    NAV_TXN_LEDGER,
    NAV_VENDORS,
    NAV_WORKERS,
    NAV_YEAR_END_CLOSE,
)

# Streamlit nav_selection / _PAGE_DISPATCH keys (text-only; icons via icon_svg.py).
NAV_PAGE_I18N: dict[str, str] = {
    NAV_HOME: "nav.home",
    NAV_TODAY_SUMMARY: "nav.today_summary",
    NAV_NEW_TRANSACTION: "nav.new_transaction",
    NAV_TXN_LEDGER: "nav.transaction_ledger",
    NAV_SALES: "nav.sales",
    NAV_EXPENSES: "nav.expenses",
    NAV_RECURRING_EXPENSES: "nav.recurring_expenses",
    NAV_PURCHASES: "nav.purchases",
    NAV_CASH_RECONCILIATION: "nav.cash_reconciliation",
    NAV_EXTERNAL_SALES_VERIFICATION: "nav.external_sales_verification",
    NAV_END_OF_DAY_CLOSE: "nav.end_of_day_close",
    NAV_RC_INGREDIENTS: "nav.rc_ingredients",
    NAV_RC_RECIPES: "nav.rc_recipes",
    NAV_RC_COST_BREAKDOWN: "nav.rc_cost_breakdown",
    NAV_RC_MENU_ITEMS: "nav.rc_menu_items",
    NAV_CUSTOMERS: "nav.customers",
    NAV_VENDORS: "nav.vendors",
    NAV_RECEIVABLES: "nav.receivables",
    NAV_PAYABLES: "nav.payables",
    NAV_INVENTORY: "nav.inventory",
    NAV_BANKING: "nav.banking",
    NAV_REPORTS: "nav.reports",
    NAV_PROFIT_LOSS: "nav.profit_loss",
    NAV_BALANCE_SHEET: "nav.balance_sheet",
    NAV_CASH_FLOW: "nav.cash_flow",
    NAV_GENERAL_LEDGER: "nav.general_ledger",
    NAV_TRIAL_BALANCE: "nav.trial_balance",
    NAV_JOURNAL_ENTRIES: "nav.journal_entries",
    NAV_FISCAL_PERIODS: "nav.fiscal_periods",
    NAV_YEAR_END_CLOSE: "nav.year_end_close",
    NAV_BUDGET: "nav.budget",
    NAV_CHART_OF_ACCOUNTS: "nav.chart_of_accounts",
    NAV_RECON_HEALTH: "nav.recon_health",
    NAV_PARTNER_ACCOUNTS: "nav.partner_accounts",
    NAV_WORKERS: "nav.workers",
    NAV_COMPANY_SETTINGS: "nav.company_settings",
    NAV_MEMBERS: "nav.members",
    NAV_AUDIT_LOG: "nav.audit_log",
    NAV_BACKUP_RESTORE: "nav.backup_restore",
    NAV_OPENING_BALANCES: "nav.opening_balances",
    NAV_PERMISSIONS: "nav.permissions",
    NAV_MY_ACCOUNT: "nav.my_account",
}
