"""Code-first settings registry — Phase 14D-B2a.

YAML-equivalent metadata stored as Python for zero extra dependencies.
"""

from registry.types import LockRules, SettingDef

_LOCK_CURRENCY = LockRules(after_first_post="block", after_year_end_close="block")
_LOCK_FISCAL_MONTH = LockRules(after_first_post="block", after_year_end_close="block")
_LOCK_FX = LockRules(after_first_post="allow", after_first_fx_transaction="block")
_LOCK_VAT = LockRules(after_first_post="allow", after_first_tax_invoice="block")
_WARN_NAME = LockRules(after_first_post="warn")

SETTINGS: tuple[SettingDef, ...] = (
    # ── Company profile (live storage) ───────────────────────────────────────
    SettingDef(
        key="company.display_name",
        scope="company",
        type="string",
        group="company",
        label_key="settings.company.display_name",
        default="My Company",
        storage="company_column",
        legacy_key="company_name",
        company_column="name",
        lock=_WARN_NAME,
        audit=True,
    ),
    SettingDef(
        key="company.legal_name",
        scope="company",
        type="string",
        group="company",
        label_key="settings.company.legal_name",
        default=None,
        storage="company_column",
        company_column="full_name",
        audit=True,
    ),
    SettingDef(
        key="company.email",
        scope="company",
        type="email",
        group="company",
        label_key="settings.company.email",
        default="",
        storage="company_column",
        legacy_key="company_email",
        company_column="email",
        audit=True,
    ),
    SettingDef(
        key="company.phone",
        scope="company",
        type="phone",
        group="company",
        label_key="settings.company.phone",
        default="",
        storage="company_column",
        legacy_key="company_phone",
        company_column="phone",
        audit=True,
    ),
    SettingDef(
        key="company.address",
        scope="company",
        type="text",
        group="company",
        label_key="settings.company.address",
        default="",
        storage="company_setting",
        legacy_key="company_address",
        audit=True,
    ),
    SettingDef(
        key="company.tax_number",
        scope="company",
        type="string",
        group="company",
        label_key="settings.company.tax_number",
        default="",
        storage="company_setting",
        legacy_key="company_tax_number",
        audit=True,
    ),
    SettingDef(
        key="company.logo_url",
        scope="company",
        type="string",
        group="company",
        label_key="settings.company.logo_url",
        default="",
        storage="company_setting",
        legacy_key="company_logo_url",
        audit=True,
    ),
    SettingDef(
        key="company.timezone",
        scope="company",
        type="timezone",
        group="company",
        label_key="settings.company.timezone",
        default="Europe/Istanbul",
        storage="virtual",
        planned=True,
        lock=LockRules(after_first_post="warn"),
        audit=True,
        enforce_in=("eod.close", "reports"),
    ),
    SettingDef(
        key="company.date_format",
        scope="company",
        type="date_format",
        group="company",
        label_key="settings.company.date_format",
        default="DD.MM.YYYY",
        storage="virtual",
        planned=True,
        audit=True,
    ),
    SettingDef(
        key="company.number_format",
        scope="company",
        type="number_format",
        group="company",
        label_key="settings.company.number_format",
        default="tr-TR",
        storage="virtual",
        planned=True,
        audit=True,
    ),
    SettingDef(
        key="company.document_language",
        scope="company",
        type="language_code",
        group="company",
        label_key="settings.company.document_language",
        default="en",
        storage="company_setting",
        legacy_key="company.document_language",
        options=("en", "tr"),
        audit=True,
    ),
    # ── Accounting (partially live) ────────────────────────────────────────
    SettingDef(
        key="accounting.base_currency",
        scope="company",
        type="currency_code",
        group="accounting",
        label_key="settings.accounting.base_currency",
        default="TRY",
        storage="company_setting",
        legacy_key="currency",
        options=("TRY", "USD", "EUR", "GBP"),
        lock=_LOCK_CURRENCY,
        dangerous_after_transactions=True,
        audit=True,
        enforce_in=("posting", "reports", "fx"),
    ),
    SettingDef(
        key="accounting.default_tax_rate",
        scope="company",
        type="percent",
        group="accounting",
        label_key="settings.accounting.default_tax_rate",
        default=0.0,
        storage="company_setting",
        legacy_key="tax_rate",
        lock=LockRules(after_first_post="warn"),
        audit=True,
        enforce_in=("sales", "purchases"),
    ),
    SettingDef(
        key="accounting.fiscal_year_label",
        scope="company",
        type="string",
        group="accounting",
        label_key="settings.accounting.fiscal_year_label",
        default="2026",
        storage="company_setting",
        legacy_key="financial_year",
        description="Legacy year label used in UI today; not fiscal start month.",
        audit=True,
    ),
    SettingDef(
        key="accounting.fiscal_year_start_month",
        scope="company",
        type="int",
        group="accounting",
        label_key="settings.accounting.fiscal_year_start_month",
        default=1,
        storage="virtual",
        planned=True,
        lock=_LOCK_FISCAL_MONTH,
        dangerous_after_transactions=True,
        audit=True,
        enforce_in=("fiscal.close", "year_end.close"),
    ),
    SettingDef(
        key="accounting.multi_currency_enabled",
        scope="company",
        type="bool",
        group="accounting",
        label_key="settings.accounting.multi_currency_enabled",
        default=False,
        storage="virtual",
        planned=True,
        lock=_LOCK_FX,
        audit=True,
        enforce_in=("fx",),
    ),
    SettingDef(
        key="accounting.coa_template",
        scope="company",
        type="enum",
        group="accounting",
        label_key="settings.accounting.coa_template",
        default="standard",
        storage="virtual",
        planned=True,
        options=("standard",),
        lock=LockRules(after_first_post="block"),
        audit=True,
        enforce_in=("coa.seed",),
        description="Used by Phase 14D-C per-company COA seeding.",
    ),
    SettingDef(
        key="accounting.tax_inclusive_prices",
        scope="company",
        type="bool",
        group="accounting",
        label_key="settings.accounting.tax_inclusive_prices",
        default=False,
        storage="virtual",
        planned=True,
        audit=True,
    ),
    # ── Banking & reconciliation (Phase 18-MVP-1) ────────────────────────────
    # All OFF by default => posting behaviour identical to pre-Phase-18.
    SettingDef(
        key="banking.reconciliation_enabled",
        scope="company",
        type="bool",
        group="banking",
        label_key="settings.banking.reconciliation_enabled",
        default=False,
        storage="company_setting",
        legacy_key="banking.reconciliation_enabled",
        audit=True,
        enforce_in=("banking.reconciliation",),
        description="Master toggle for the statement reconciliation workspace.",
    ),
    SettingDef(
        key="banking.company_card_enabled",
        scope="company",
        type="bool",
        group="banking",
        label_key="settings.banking.company_card_enabled",
        default=False,
        storage="company_setting",
        legacy_key="banking.company_card_enabled",
        audit=True,
        enforce_in=("banking.reconciliation",),
        description="Company-owned credit card as a payment source.",
    ),
    SettingDef(
        key="banking.bank_charges_enabled",
        scope="company",
        type="bool",
        group="banking",
        label_key="settings.banking.bank_charges_enabled",
        default=False,
        storage="company_setting",
        legacy_key="banking.bank_charges_enabled",
        audit=True,
        enforce_in=("banking.reconciliation",),
        description="Fee/charge step (some countries have no such charges).",
    ),
    SettingDef(
        key="banking.card_settlement_enabled",
        scope="company",
        type="bool",
        group="banking",
        label_key="settings.banking.card_settlement_enabled",
        default=False,
        storage="company_setting",
        legacy_key="banking.card_settlement_enabled",
        audit=True,
        enforce_in=("sales", "banking.reconciliation"),
        description="Route card sales through Card Sales Clearing instead of straight to Bank.",
    ),
    SettingDef(
        key="banking.card_sales_clearing_backfill",
        scope="company",
        type="enum",
        group="banking",
        label_key="settings.banking.card_sales_clearing_backfill",
        default="none",
        storage="company_setting",
        legacy_key="banking.card_sales_clearing_backfill",
        options=("none", "reclassify_to_clearing"),
        audit=True,
        enforce_in=("banking.reconciliation",),
        description="How existing card sales already posted to Bank are treated when settlement is enabled.",
    ),
    SettingDef(
        key="banking.transfer_fee_threshold",
        scope="company",
        type="float",
        group="banking",
        label_key="settings.banking.transfer_fee_threshold",
        default=0.0,
        storage="company_setting",
        legacy_key="banking.transfer_fee_threshold",
        audit=True,
        enforce_in=("banking.reconciliation",),
        description="Hint when posting withdrawals above this amount that a separate bank transfer fee may appear (0 = off).",
    ),
    # ── Policies (metadata only — enforcement deferred) ──────────────────────
    SettingDef(
        key="policy.accounting_mode",
        scope="company",
        type="accounting_mode",
        group="policy",
        label_key="settings.policy.accounting_mode",
        default="flexible",
        storage="company_setting",
        legacy_key="policy.accounting_mode",
        options=("flexible", "standard", "strict"),
        audit=True,
        enforce_in=("posting",),
    ),
    SettingDef(
        key="policy.eod_close",
        scope="company",
        type="policy_level",
        group="policy",
        label_key="settings.policy.eod_close",
        default="recommended",
        storage="virtual",
        planned=True,
        options=("not_required", "recommended", "required"),
        audit=True,
        enforce_in=("eod.close",),
    ),
    SettingDef(
        key="policy.cash_reconciliation",
        scope="company",
        type="policy_level",
        group="policy",
        label_key="settings.policy.cash_reconciliation",
        default="recommended",
        storage="virtual",
        planned=True,
        options=("not_required", "recommended", "required"),
        audit=True,
        enforce_in=("banking.cash_recon",),
    ),
    SettingDef(
        key="policy.receipt_capture",
        scope="company",
        type="enum",
        group="policy",
        label_key="settings.policy.receipt_capture",
        default="never",
        storage="virtual",
        planned=True,
        options=("never", "above_amount", "always"),
        audit=True,
        enforce_in=("sales", "expenses"),
    ),
    SettingDef(
        key="policy.receipt_amount_threshold",
        scope="company",
        type="float",
        group="policy",
        label_key="settings.policy.receipt_amount_threshold",
        default=None,
        storage="virtual",
        planned=True,
        audit=True,
        enforce_in=("sales", "expenses"),
    ),
    SettingDef(
        key="policy.period_backdating",
        scope="company",
        type="enum",
        group="policy",
        label_key="settings.policy.period_backdating",
        default="allow",
        storage="virtual",
        planned=True,
        options=("allow", "warn", "block"),
        audit=True,
        enforce_in=("posting",),
    ),
    SettingDef(
        key="policy.fiscal_period_close",
        scope="company",
        type="policy_level",
        group="policy",
        label_key="settings.policy.fiscal_period_close",
        default="required",
        storage="virtual",
        planned=True,
        options=("not_required", "recommended", "required"),
        audit=True,
        enforce_in=("fiscal.close",),
    ),
    SettingDef(
        key="policy.year_end_close",
        scope="company",
        type="policy_level",
        group="policy",
        label_key="settings.policy.year_end_close",
        default="required",
        storage="virtual",
        planned=True,
        options=("not_required", "recommended", "required"),
        audit=True,
        enforce_in=("year_end.close",),
    ),
    SettingDef(
        key="policy.vat_enabled",
        scope="company",
        type="bool",
        group="policy",
        label_key="settings.policy.vat_enabled",
        default=False,
        storage="virtual",
        planned=True,
        lock=_LOCK_VAT,
        audit=True,
        enforce_in=("vat",),
    ),
    # ── User preferences (partially live via AppSetting user_pref_*) ─────────
    SettingDef(
        key="user.theme",
        scope="user",
        type="enum",
        group="preferences",
        label_key="settings.user.theme",
        default="system",
        storage="app_setting",
        legacy_key="theme",
        options=("light", "dark", "system"),
        audit=False,
    ),
    SettingDef(
        key="user.language",
        scope="user",
        type="language_code",
        group="preferences",
        label_key="settings.user.language",
        default="en",
        storage="app_setting",
        legacy_key="language",
        options=("en", "tr"),
        audit=False,
    ),
    SettingDef(
        key="user.landing_page",
        scope="user",
        type="module_ref",
        group="preferences",
        label_key="settings.user.landing_page",
        default="dashboard",
        storage="virtual",
        planned=True,
        audit=False,
    ),
    SettingDef(
        key="user.dashboard_layout",
        scope="user",
        type="enum",
        group="preferences",
        label_key="settings.user.dashboard_layout",
        default="default",
        storage="virtual",
        planned=True,
        options=("default",),
        audit=False,
    ),
    # ── Setup / system stubs ─────────────────────────────────────────────────
    SettingDef(
        key="setup.vertical_template",
        scope="company",
        type="enum",
        group="setup",
        label_key="settings.setup.vertical_template",
        default="general",
        storage="company_setting",
        legacy_key="setup.vertical_template",
        options=("general", "services", "retail", "restaurant", "tourism"),
        audit=True,
    ),
    SettingDef(
        key="setup.wizard_completed",
        scope="company",
        type="bool",
        group="setup",
        label_key="settings.setup.wizard_completed",
        default=False,
        storage="company_setting",
        legacy_key="setup.wizard_completed",
        audit=True,
    ),
)

# Legacy keys used by load_settings() today must each map to one registry entry.
LEGACY_COMPANY_SETTING_KEYS = frozenset(
    {
        "currency",
        "tax_rate",
        "financial_year",
        "company_address",
        "company_tax_number",
        "company_logo_url",
        "setup.wizard_completed",
        "setup.vertical_template",
        "policy.accounting_mode",
        "company.document_language",
        "banking.reconciliation_enabled",
        "banking.company_card_enabled",
        "banking.bank_charges_enabled",
        "banking.card_settlement_enabled",
        "banking.card_sales_clearing_backfill",
        "banking.transfer_fee_threshold",
    }
)
LEGACY_COMPANY_DIRECT_KEYS = frozenset({"company_name", "company_email", "company_phone"})
